# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 20:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Architects_supervision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('terms_name', models.CharField(max_length=100)),
                ('terms', models.CharField(max_length=100)),
                ('cost_name', models.CharField(max_length=100)),
                ('cost', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Architecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('terms_name', models.CharField(max_length=100)),
                ('terms', models.CharField(max_length=100)),
                ('cost_name', models.CharField(max_length=100)),
                ('cost', models.CharField(max_length=100)),
                ('schematic_desing_name', models.CharField(max_length=100)),
                ('desing_development_name', models.CharField(max_length=100)),
                ('construction_documents_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Interior_design',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('paragraphs_name', models.CharField(max_length=100)),
                ('terms_name', models.CharField(max_length=100)),
                ('terms', models.CharField(max_length=100)),
                ('cost_name', models.CharField(max_length=100)),
                ('cost', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Paragraphs_Arch_CD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Paragraphs_Arch_DD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Paragraphs_Arch_SD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Paragraphs_AS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Paragraphs_ID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Paragraphs_PD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Product_design',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('paragraphs_name', models.CharField(max_length=100)),
                ('terms_name', models.CharField(max_length=100)),
                ('terms', models.CharField(max_length=100)),
                ('cost_name', models.CharField(max_length=100)),
                ('cost', models.CharField(max_length=100)),
            ],
        ),
    ]
