# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 20:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20170219_2230'),
    ]

    operations = [
        migrations.AddField(
            model_name='architects_supervision',
            name='description',
            field=models.CharField(default='some string', max_length=300),
        ),
        migrations.AddField(
            model_name='architecture',
            name='description',
            field=models.CharField(default='some string', max_length=300),
        ),
        migrations.AddField(
            model_name='interior_design',
            name='description',
            field=models.CharField(default='some string', max_length=300),
        ),
        migrations.AddField(
            model_name='product_design',
            name='description',
            field=models.CharField(default='some string', max_length=300),
        ),
    ]
