# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 21:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20170219_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='architecture',
            name='construction_documents_description',
            field=models.CharField(default='description', max_length=100),
        ),
    ]
