# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 00:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_architecture_construction_documents_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arch_projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=600)),
                ('mainimg', models.ImageField(upload_to='static/img/')),
            ],
        ),
    ]
