# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 00:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_auto_20170227_0206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arch_projects',
            name='mainimg',
            field=models.ImageField(upload_to='mainapp/static/img/arch/'),
        ),
    ]
