# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 20:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_auto_20170227_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arch_projects',
            name='mainimg',
            field=models.ImageField(upload_to='/static/img/arch/'),
        ),
    ]
