# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 21:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_auto_20170227_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arch_projects',
            name='mainimg',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
