# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 22:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_auto_20170228_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arch_projects',
            name='mainimg',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
