# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0015_auto_20170228_0052'),
    ]

    operations = [
        migrations.AddField(
            model_name='arch_projects',
            name='side',
            field=models.CharField(default='L', max_length=20),
        ),
    ]
