# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 22:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0016_arch_projects_side'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arch_photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archimg', models.FileField(null=True, upload_to='')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Arch_projects')),
            ],
        ),
    ]
