# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 19:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0017_arch_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='arch_projects',
            name='mainimgchange',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
