# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-09 23:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0019_auto_20170608_1817'),
    ]

    operations = [
        migrations.CreateModel(
            name='Design_photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designimg', models.FileField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Design_projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=300)),
                ('name_ru', models.CharField(max_length=300)),
                ('name_ua', models.CharField(max_length=300)),
                ('description_en', models.CharField(max_length=600)),
                ('description_ru', models.CharField(max_length=600)),
                ('description_ua', models.CharField(max_length=600)),
                ('mainimg', models.FileField(null=True, upload_to='')),
                ('side', models.CharField(default='L', max_length=20)),
            ],
        ),
        migrations.RenameField(
            model_name='arch_projects',
            old_name='description',
            new_name='description_en',
        ),
        migrations.RenameField(
            model_name='arch_projects',
            old_name='name',
            new_name='name_en',
        ),
        migrations.AddField(
            model_name='arch_projects',
            name='description_ru',
            field=models.CharField(default=1, max_length=600),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='arch_projects',
            name='description_ua',
            field=models.CharField(default=1, max_length=600),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='arch_projects',
            name='name_ru',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='arch_projects',
            name='name_ua',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='design_photo',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Design_projects'),
        ),
    ]
