# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-07 21:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0020_auto_20170610_0227'),
    ]

    operations = [
        migrations.AddField(
            model_name='arch_projects',
            name='number',
            field=models.IntegerField(default='1'),
        ),
        migrations.AddField(
            model_name='design_projects',
            name='number',
            field=models.IntegerField(default='1'),
        ),
    ]
