# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-18 21:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0022_auto_20170815_0136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arch_projects',
            name='side',
        ),
        migrations.RemoveField(
            model_name='design_projects',
            name='side',
        ),
        migrations.AlterField(
            model_name='arch_projects',
            name='description_en',
            field=models.CharField(max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='arch_projects',
            name='description_ru',
            field=models.CharField(max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='arch_projects',
            name='description_ua',
            field=models.CharField(max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='design_projects',
            name='description_en',
            field=models.CharField(max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='design_projects',
            name='description_ru',
            field=models.CharField(max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='design_projects',
            name='description_ua',
            field=models.CharField(max_length=600, null=True),
        ),
    ]
