# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-18 21:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0023_auto_20170819_0035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arch_projects',
            name='description_en',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='arch_projects',
            name='description_ru',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='arch_projects',
            name='description_ua',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='design_projects',
            name='description_en',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='design_projects',
            name='description_ru',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='design_projects',
            name='description_ua',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
    ]
