# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-18 21:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0024_auto_20170819_0037'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.FileField(null=True, upload_to='')),
                ('link', models.CharField(max_length=300)),
                ('number', models.IntegerField(default='1')),
            ],
        ),
    ]
